import re

def convert(sql_path, out_path):
    with open(sql_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Match CREATE TABLE statements to extract table definitions
    tables = []
    
    # Simple regex to get table name and inner content
    pattern = r"CREATE TABLE `([^`]+)` \((.*?)\) ENGINE=InnoDB[^;]+;"
    
    matches = re.finditer(pattern, content, re.DOTALL)
    
    pg_sql = "-- PostgreSQL schema converted from MySQL\n\n"
    
    for match in matches:
        table_name = match.group(1)
        columns = match.group(2)
        
        # Clean up column definitions
        # 1. Remove backticks
        columns = columns.replace('`', '"')
        
        # 2. Change collations
        columns = re.sub(r' CHARACTER SET [a-zA-Z0-9_]+ COLLATE [a-zA-Z0-9_]+', '', columns)
        
        # 3. Change int(11) to integer
        columns = re.sub(r'int\(\d+\)', 'integer', columns)
        columns = re.sub(r'tinyint\(1\)', 'boolean', columns)
        
        # 4. Change datetime to timestamp
        columns = re.sub(r'datetime', 'timestamp', columns)
        
        # 5. Fix current_timestamp()
        columns = columns.replace('current_timestamp()', 'CURRENT_TIMESTAMP')
        
        # 6. Remove ON UPDATE CURRENT_TIMESTAMP
        columns = re.sub(r'ON UPDATE CURRENT_TIMESTAMP', '', columns)
        
        # 7. Convert AUTO_INCREMENT to generated by default as identity
        # In PG 10+ we use generated columns, but for Supabase serial or integer generated by default works.
        # Since identity is cleaner:
        columns = columns.replace('NOT NULL AUTO_INCREMENT', 'integer generated by default as identity NOT NULL')
        
        # 8. ENUM conversion (we'll just use text for simplicity and rely on CHECK constraints if needed, or just leave as text)
        # To make it robust without creating types, convert enum(...) to text CHECK (col in (...))
        def enum_replacer(m):
            return "text CHECK (" + m.group(1) + ")"
        # It's tricky to do correctly with regex if we don't know the column name easily. 
        # Safer: convert enum to text
        columns = re.sub(r'enum\([^\)]+\)', 'text', columns)
        
        # 9. Clean up keys (MySQL puts primary key and foreign keys inside the CREATE TABLE, PG too, but syntaxes differ slightly)
        # Actually, extracting standard PK is fine if it's PRIMARY KEY ("id")
        
        pg_sql += f"CREATE TABLE \"{table_name}\" (\n{columns}\n);\n\n"

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(pg_sql)

convert('squema.sql', 'schema_pg.sql')
