-- PostgreSQL schema for IO Group (Converted for Supabase)

CREATE TABLE "AuditLog" (
  "id_log" bigint generated by default as identity PRIMARY KEY,
  "id_usuario" integer DEFAULT NULL,
  "tabla_afectada" varchar(50) NOT NULL,
  "id_registro" integer DEFAULT NULL,
  "accion" text NOT NULL,
  "datos_anteriores" jsonb DEFAULT NULL,
  "datos_nuevos" jsonb DEFAULT NULL,
  "ip_address" varchar(45) DEFAULT NULL,
  "fecha_hora" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "CalendarioRecojo" (
  "id" bigint generated by default as identity PRIMARY KEY,
  "mes" integer NOT NULL,
  "anio" integer NOT NULL,
  "dias_json" jsonb DEFAULT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Cliente" (
  "id_cliente" bigint generated by default as identity PRIMARY KEY,
  "nombre" varchar(100) NOT NULL,
  "tipo_documento" text DEFAULT 'DNI',
  "dni" varchar(15) DEFAULT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ContratoLaboral" (
  "id_contrato_laboral" bigint generated by default as identity PRIMARY KEY,
  "id_empleado" integer NOT NULL,
  "cargo" varchar(100) NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date DEFAULT NULL,
  "sueldo" numeric(10,2) DEFAULT NULL,
  "tipo_contrato" text DEFAULT 'indefinido',
  "doc_escaneado" varchar(255) DEFAULT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ContratoServicio" (
  "id_contrato" bigint generated by default as identity PRIMARY KEY,
  "id_sede" integer NOT NULL,
  "fecha_inicio" date NOT NULL,
  "fecha_fin" date DEFAULT NULL,
  "frecuencia" text NOT NULL,
  "peso_limite_kg" numeric(10,2) DEFAULT NULL,
  "tarifa_adicional_kg" numeric(10,2) DEFAULT NULL,
  "tarifa" numeric(10,2) NOT NULL,
  "tipo_tarifa" text DEFAULT 'por_servicio',
  "doc_escaneado" varchar(255) DEFAULT NULL,
  "comprobante_pago" varchar(500) DEFAULT NULL,
  "observaciones" text DEFAULT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Egreso" (
  "id_egreso" bigint generated by default as identity PRIMARY KEY,
  "categoria" text NOT NULL,
  "subcategoria" varchar(50) NOT NULL,
  "descripcion" varchar(255) NOT NULL,
  "monto" numeric(10,2) NOT NULL,
  "fecha" date NOT NULL,
  "id_ruta" integer DEFAULT NULL,
  "id_vehiculo" integer DEFAULT NULL,
  "comprobante" varchar(100) DEFAULT NULL,
  "observaciones" text DEFAULT NULL,
  "id_usuario" integer NOT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "EgresoSubcategoria" (
  "id_subcategoria" bigint generated by default as identity PRIMARY KEY,
  "categoria" text NOT NULL,
  "nombre" varchar(50) NOT NULL,
  "descripcion" varchar(100) DEFAULT NULL,
  "activo" boolean DEFAULT true
);

CREATE TABLE "Empleado" (
  "id_empleado" bigint generated by default as identity PRIMARY KEY,
  "dni" varchar(8) NOT NULL,
  "nombres" varchar(100) NOT NULL,
  "apellidos" varchar(100) NOT NULL,
  "telefono" varchar(20) DEFAULT NULL,
  "email" varchar(100) DEFAULT NULL,
  "direccion" varchar(255) DEFAULT NULL,
  "fecha_nacimiento" date DEFAULT NULL,
  "licencia_conducir" varchar(20) DEFAULT NULL,
  "categoria_licencia" varchar(10) DEFAULT NULL,
  "fecha_venc_licencia" date DEFAULT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Empresa" (
  "id_empresa" bigint generated by default as identity PRIMARY KEY,
  "id_cliente" integer NOT NULL,
  "razon_social" varchar(200) NOT NULL,
  "rubro" varchar(100) DEFAULT NULL,
  "ruc" varchar(11) NOT NULL,
  "direccion_fiscal" varchar(255) DEFAULT NULL,
  "distrito" varchar(100) DEFAULT NULL,
  "provincia" varchar(100) DEFAULT NULL,
  "departamento" varchar(100) DEFAULT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Factura" (
  "id_factura" bigint generated by default as identity PRIMARY KEY,
  "id_servicio" integer NOT NULL,
  "numero_factura" varchar(50) NOT NULL,
  "doc_escaneado" varchar(500) DEFAULT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "FirmaDigital" (
  "id_firma" bigint generated by default as identity PRIMARY KEY,
  "id_proceso" integer NOT NULL,
  "token" varchar(64) NOT NULL,
  "firmado" boolean DEFAULT false,
  "firma_imagen" varchar(500) DEFAULT NULL,
  "ip_firmante" varchar(45) DEFAULT NULL,
  "user_agent" text DEFAULT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_firma" timestamp with time zone DEFAULT NULL
);

CREATE TABLE "GestionCobranza" (
  "id" bigint generated by default as identity PRIMARY KEY,
  "id_servicio" integer NOT NULL,
  "id_sede" integer NOT NULL,
  "tipo_gestion" text NOT NULL,
  "resultado" text NOT NULL,
  "observaciones" text DEFAULT NULL,
  "fecha_proxima_gestion" date DEFAULT NULL,
  "gestionado_por" integer DEFAULT NULL,
  "fecha_gestion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Guia" (
  "id_guia" bigint generated by default as identity PRIMARY KEY,
  "id_servicio" integer NOT NULL,
  "serie" varchar(10) DEFAULT NULL,
  "numero_guia" varchar(20) NOT NULL,
  "fecha_emision" date DEFAULT NULL,
  "punto_partida" varchar(255) DEFAULT NULL,
  "punto_llegada" varchar(255) DEFAULT NULL,
  "doc_escaneado" varchar(255) DEFAULT NULL,
  "observaciones" text DEFAULT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "IngresoNuevoCliente" (
  "id" bigint generated by default as identity PRIMARY KEY,
  "id_contrato" integer NOT NULL,
  "id_sede" integer NOT NULL,
  "meses_pagados" integer NOT NULL,
  "monto_total" numeric(10,2) NOT NULL,
  "fecha_pago" date NOT NULL,
  "metodo_pago" varchar(50) DEFAULT NULL,
  "observaciones" text DEFAULT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Manifiesto" (
  "id_manifiesto" bigint generated by default as identity PRIMARY KEY,
  "id_servicio" integer NOT NULL,
  "numero_manifiesto" varchar(50) DEFAULT NULL,
  "tipo_residuo" varchar(100) DEFAULT NULL,
  "codigo_residuo" varchar(20) DEFAULT NULL,
  "descripcion_residuo" text DEFAULT NULL,
  "peso_kg" numeric(10,2) DEFAULT NULL,
  "unidad_medida" varchar(20) DEFAULT 'kg',
  "cantidad_bultos" integer DEFAULT NULL,
  "nombre_responsable" varchar(100) DEFAULT NULL,
  "cargo_responsable" varchar(100) DEFAULT NULL,
  "dni_responsable" varchar(15) DEFAULT NULL,
  "doc_escaneado" varchar(255) DEFAULT NULL,
  "observaciones" text DEFAULT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "NewsletterSubscriber" (
  "id_subscriber" bigint generated by default as identity PRIMARY KEY,
  "email" varchar(255) NOT NULL,
  "nombre" varchar(100) DEFAULT NULL,
  "codigo_descuento" varchar(50) NOT NULL,
  "descuento_usado" boolean DEFAULT false,
  "activo" boolean DEFAULT true,
  "ip_address" varchar(45) DEFAULT NULL,
  "user_agent" text DEFAULT NULL,
  "pagina_origen" varchar(255) DEFAULT NULL,
  "fecha_suscripcion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_uso_descuento" timestamp with time zone DEFAULT NULL
);

CREATE TABLE "Planta" (
  "id_planta" bigint generated by default as identity PRIMARY KEY,
  "razon_social" varchar(200) NOT NULL,
  "ruc" varchar(11) NOT NULL,
  "nombre_comercial" varchar(200) DEFAULT NULL,
  "direccion" varchar(255) NOT NULL,
  "distrito" varchar(100) DEFAULT NULL,
  "provincia" varchar(100) DEFAULT NULL,
  "departamento" varchar(100) DEFAULT NULL,
  "tipo_tratamiento" varchar(100) DEFAULT NULL,
  "codigo_eps" varchar(50) DEFAULT NULL,
  "telefono" varchar(20) DEFAULT NULL,
  "contacto_nombre" varchar(100) DEFAULT NULL,
  "contacto_email" varchar(100) DEFAULT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ProcesoAlta" (
  "id_proceso" bigint generated by default as identity PRIMARY KEY,
  "datos_json" jsonb NOT NULL,
  "etapa_actual" integer DEFAULT 1,
  "id_usuario_creador" integer DEFAULT NULL,
  "id_usuario_modificador" integer DEFAULT NULL,
  "doc_generado" varchar(255) DEFAULT NULL,
  "doc_firmado" varchar(255) DEFAULT NULL,
  "comprobante_pago" varchar(255) DEFAULT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Prospecto" (
  "id_prospecto" bigint generated by default as identity PRIMARY KEY,
  "nombre_comercial" varchar(200) NOT NULL,
  "tipo_cliente" text DEFAULT 'persona',
  "ruc" varchar(11) DEFAULT NULL,
  "dni" varchar(15) DEFAULT NULL,
  "telefono" varchar(20) DEFAULT NULL,
  "email" varchar(100) DEFAULT NULL,
  "direccion" varchar(255) DEFAULT NULL,
  "distrito" varchar(100) DEFAULT NULL,
  "fuente" varchar(50) DEFAULT NULL,
  "estado" text DEFAULT 'nuevo',
  "valor_potencial" numeric(10,2) DEFAULT NULL,
  "notas" text DEFAULT NULL,
  "id_usuario_asignado" integer DEFAULT NULL,
  "fecha_proximo_contacto" date DEFAULT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Ruta" (
  "id_ruta" bigint generated by default as identity PRIMARY KEY,
  "id_vehiculo" integer NOT NULL,
  "codigo_ruta" varchar(50) DEFAULT NULL,
  "fecha" date NOT NULL,
  "hora_salida" time DEFAULT NULL,
  "hora_retorno" time DEFAULT NULL,
  "km_inicial" integer DEFAULT NULL,
  "km_final" integer DEFAULT NULL,
  "estado" text DEFAULT 'programada',
  "observaciones" text DEFAULT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "id_chofer" integer DEFAULT NULL,
  "id_ayudante" integer DEFAULT NULL
);

CREATE TABLE "Sede" (
  "id_sede" bigint generated by default as identity PRIMARY KEY,
  "id_empresa" integer NOT NULL,
  "nombre_comercial" varchar(200) NOT NULL,
  "direccion" varchar(255) NOT NULL,
  "distrito" varchar(100) DEFAULT NULL,
  "provincia" varchar(100) DEFAULT NULL,
  "departamento" varchar(100) DEFAULT NULL,
  "region" varchar(20) DEFAULT NULL,
  "referencia" text DEFAULT NULL,
  "coordenadas_gps" varchar(50) DEFAULT NULL,
  "contacto_nombre" varchar(100) DEFAULT NULL,
  "contacto_telefono" varchar(20) DEFAULT NULL,
  "contacto_telefono_2" varchar(20) DEFAULT NULL,
  "contacto_email" varchar(100) DEFAULT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Servicio" (
  "id_servicio" bigint generated by default as identity PRIMARY KEY,
  "id_sede" integer NOT NULL,
  "id_ruta" integer DEFAULT NULL,
  "id_planta" integer DEFAULT NULL,
  "id_contrato" integer DEFAULT NULL,
  "mes_servicio" varchar(50) DEFAULT NULL,
  "fecha_ejecucion" date DEFAULT NULL,
  "estado" text DEFAULT 'completado',
  "estado_pago" text DEFAULT 'pendiente',
  "fecha_pago" date DEFAULT NULL,
  "forma_pago" varchar(50) DEFAULT NULL,
  "residuo" text DEFAULT NULL,
  "observaciones" text DEFAULT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "ServicioEmpleado" (
  "id_servicio_empleado" bigint generated by default as identity PRIMARY KEY,
  "id_servicio" integer NOT NULL,
  "id_empleado" integer NOT NULL,
  "rol" text DEFAULT 'ayudante',
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Usuario" (
  "id_usuario" bigint generated by default as identity PRIMARY KEY,
  "username" varchar(50) NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "nombre_completo" varchar(100) NOT NULL,
  "rol" text DEFAULT 'viewer',
  "email" varchar(100) DEFAULT NULL,
  "activo" boolean DEFAULT true,
  "ultimo_acceso" timestamp with time zone DEFAULT NULL,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "UsuarioPermiso" (
  "id_permiso" bigint generated by default as identity PRIMARY KEY,
  "id_usuario" integer NOT NULL,
  "modulo" varchar(50) NOT NULL,
  "puede_ver" boolean DEFAULT true,
  "puede_editar" boolean DEFAULT false,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Vehiculo" (
  "id_vehiculo" bigint generated by default as identity PRIMARY KEY,
  "placa" varchar(10) NOT NULL,
  "marca" varchar(50) DEFAULT NULL,
  "modelo" varchar(50) DEFAULT NULL,
  "anio" integer DEFAULT NULL,
  "color" varchar(30) DEFAULT NULL,
  "tonelaje_max" numeric(6,2) DEFAULT NULL,
  "tipo" text DEFAULT 'camion',
  "numero_motor" varchar(50) DEFAULT NULL,
  "numero_chasis" varchar(50) DEFAULT NULL,
  "fecha_venc_soat" date DEFAULT NULL,
  "fecha_venc_revision" date DEFAULT NULL,
  "fecha_venc_mtc" date DEFAULT NULL,
  "activo" boolean DEFAULT true,
  "fecha_creacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  "fecha_modificacion" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);
